unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

set -g prefix C-s

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
#set -g @vim_navigator_mapping_left "C-s C-h"  # use C-h and C-Left
#set -g @vim_navigator_mapping_right "C-Right C-l"
#
#set -g @vim_navigator_mapping_up "C-s"
#set -g @vim_navigator_mapping_down "C-j"
#set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding


set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g status-position top

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
